---
title: "Chapter Draft: WIP"
subtitle: "A Sub Title"
version: "Draft v0.1"

author:
    name: Stuart Gow
    affiliations:
      - name: University of Stirling
        group: Faculty of Natural Sciences
        department: Division of Computing Science and Mathematics
date: 30 May 2025
date-format: "D MMMM YYYY"

code-fold: true
highlight-style: atom-one-light

# References, citation format
bibliography: ../Report_Quarto_Production/References/references.bib
csl: ../Report_Quarto_Production/References/ieee.csl
link-citations: true

# PDF Formatting
format:
    pdf: 
        documentclass: scrartcl
        papersize: a4
        fontsize: 11pt
        indent: true

        include-in-header:
            text: |
                % Adjust paragraph spacing
                \setlength{\parskip}{0.5em} 
                % With draft version number, date for use until published
                \usepackage{datetime}
                \newdateformat{mydateformat}{\twodigit{\THEDAY}/\twodigit{\THEMONTH}/\THEYEAR}
                \newcommand{\drafttext}{\small {{< meta version >}}, \mydateformat\today}
                \usepackage{scrlayer-scrpage}
                \lohead[\drafttext]{\drafttext}
        toc: true

        toc-title: "Table of Contents"
        # toc-depth: 2
        lof: true
        lot: true
        number-sections: true
        # number-depth: 2
---

\clearpage

# Report Section Drafting - Template

## Test Subsection

Dixi omni quas re se poni is eram. Una mundo tangi sub tam capax porro vel talia sonum. Dulcedinem praecipuum vox desiderant hic hauriantur sed tractandae. Realiter reperiri collecta at an in. Quodque ne im ab ex hominem usitata apertum. Tum judicium sua age automata eos quicquam. Si confirmari persuadeor praemissae satyriscos cogitantem et et. Cavillandi conjunctam credidisse de ex dissimilem gi integritas imaginandi. Examino plausum sub attendo hos.

Dixi omni quas re se poni is eram. Una mundo tangi sub tam capax porro vel talia sonum. Dulcedinem praecipuum vox desiderant hic hauriantur sed tractandae. Realiter reperiri collecta at an in. Quodque ne im ab ex hominem usitata apertum. Tum judicium sua age automata eos quicquam. Si confirmari persuadeor praemissae satyriscos cogitantem et et. Cavillandi conjunctam credidisse de ex dissimilem gi integritas imaginandi. Examino plausum sub attendo hos.

And use @donoghue2020

### Test Lower Level

Mentemque persuadet ei opportune de aggredior proponere. Imaginabar objectioni indefinite ne ab propositio. Ex vera iste quam mo mihi fere post. Rogo meae imo bono aër vidi non sint. In refutent ea utrimque extensio re tractare ex rationem. Dixi omni quas re se poni is eram. Una mundo tangi sub tam capax porro vel talia sonum. Dulcedinem praecipuum vox desiderant hic hauriantur sed tractandae. Realiter reperiri collecta at an in. Quodque ne im ab ex hominem usitata apertum. Tum judicium sua age automata eos quicquam. Si confirmari persuadeor praemissae satyriscos cogitantem et et. Cavillandi conjunctam credidisse de ex dissimilem gi integritas imaginandi. Examino plausum sub attendo hos.

#### Even Lower Test Section

Dixi omni quas re se poni is eram. Una mundo tangi sub tam capax porro vel talia sonum. Dulcedinem praecipuum vox desiderant hic hauriantur sed tractandae. Realiter reperiri collecta at an in. Quodque ne im ab ex hominem usitata apertum. Tum judicium sua age automata eos quicquam. Si confirmari persuadeor praemissae satyriscos cogitantem et et. Cavillandi conjunctam credidisse de ex dissimilem gi integritas imaginandi. Examino plausum sub attendo hos.

#### Even Lower Test Section

Dixi omni quas re se poni is eram. Una mundo tangi sub tam capax porro vel talia sonum. Dulcedinem praecipuum vox desiderant hic hauriantur sed tractandae. Realiter reperiri collecta at an in. Quodque ne im ab ex hominem usitata apertum. Tum judicium sua age automata eos quicquam. Si confirmari persuadeor praemissae satyriscos cogitantem et et. Cavillandi conjunctam credidisse de ex dissimilem gi integritas imaginandi. Examino plausum sub attendo hos.

\clearpage

# References {.unnumbered}

\begingroup
\raggedright

::: {#refs}
:::

\endgroup